type IconProps = Pick<React.SVGProps<SVGSVGElement>, "className" | "style"> & {
  variant:
    | "arrowDown"
    | "arrowLeft"
    | "arrowRight"
    | "arrowUp"
    | "backward"
    | "box"
    | "center"
    | "close"
    | "downloadFile"
    | "eraser"
    | "error"
    | "forward"
    | "home"
    | "interrogation"
    | "merge"
    | "minus"
    | "pause"
    | "play"
    | "plus"
    | "reset"
    | "roundedPlay"
    | "spaceBar"
    | "spinner"
    | "split"
    | "stack"
    | "success"
    | "trash"
    | "uploadFile"
    | "warning"
    | "zoomIn"
    | "zoomOut";
};

export default IconProps;
