name: Deploy app
permissions: write-all
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}
jobs:
  deploy-app:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Check if the type is 'tag'
        if: ${{ github.event_name == 'workflow_dispatch' && github.ref_type != 'tag' }}
        run: |
          echo "::error::Workflow needs to be dispatched from a tag"
          exit 1
        shell: bash
      - name: Get version from tag
        id: get-version-from-tag
        uses: frabert/replace-string-action@v2
        with:
          pattern: ^v(\d+)\.(\d+)\.(\d+)$
          replace-with: $1.$2.$3
          string: ${{ github.ref_name }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract version from package
        id: extract-version-from-package
        uses: sergeysova/jq-action@v2
        with:
          cmd: jq .version package.json -r
      - name: Verify versions match
        if: ${{ steps.get-version-from-tag.outputs.replaced != steps.extract-version-from-package.outputs.value }}
        run: |
          echo "::error::Version in the package.json and tag don't match"
          exit 1
        shell: bash
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 22.14
      - name: Install dependencies
        run: npm ci --ignore-scripts
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check
        run: npm run check
        shell: bash
      - name: Test
        run: npm test
        shell: bash
      - name: Build
        run: npm run build
        shell: bash
        env:
          NEXT_PUBLIC_APP_VERSION: ${{ steps.get-version-from-tag.outputs.replaced }}
          NEXT_PUBLIC_BASE_PATH: /${{ github.event.repository.name }}
      - name: Configure pages
        uses: actions/configure-pages@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
